# -*- mode: ruby -*-
# vi: set ft=ruby :
SERVER_CPU = 1
SERVER_MEMORY = 1024
IP_vm1 = "10.0.0.10"
IP_vm2 = "10.0.0.11"
IP_vm3= "10.0.0.12"

Vagrant.configure("2") do |config|
  config.vm.define "lb" do |lb|
    lb.vm.box = "ubuntu/xenial64"
    lb.vm.network "private_network", ip: IP_vm1
  end
  config.vm.provider "virtualbox" do |v|
    v.cpus = SERVER_CPU
    v.memory = SERVER_MEMORY
  end

  config.vm.define "web1" do |web1|
    web1.vm.box =  "ubuntu/xenial64"
    web1.vm.network "private_network", ip: IP_vm2
  end
  config.vm.provider "virtualbox" do |v|
    v.cpus = SERVER_CPU
    v.memory = SERVER_MEMORY
  end

  config.vm.define "web2" do |web2|
    web2.vm.box =  "ubuntu/xenial64"
    web2.vm.network "private_network", ip: IP_vm3
  end
  config.vm.provider "virtualbox" do |v|
    v.cpus = SERVER_CPU
    v.memory = SERVER_MEMORY
  end
end