- name: set up webserver
  hosts: all
  vars:
    ansible_python_interpreter: auto_legacy_silent
  become: yes
  tasks: 
    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest
    - name: start nginx
      service: 
        name: nginx
        state: started
        enabled: yes  # i