# -*- mode: ruby -*-
# vi: set ft=ruby :
SERVER_CPU = 2
SERVER_MEMORY = 2048

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.network "private_network", ip:"10.0.0.10"
  config.vm.provider "virtualbox" do |v|
    v.cpus = SERVER_CPU
    v.memory = SERVER_MEMORY
    end
end
