# -*- mode: ruby -*-
# vi: set ft=ruby :
SERVER_CPU = 1
SERVER_MEMORY = 1024
IP_vm1 = "10.0.0.10"
IP_vm2 = "10.0.0.11"
IP_vm3= "10.0.0.12"

Vagrant.configure("2") do |config|
  config.vm.define "lb" do |lb|
    lb.vm.box = "ubuntu/xenial64"
    lb.vm.network "private_network", ip: IP_vm1
    lb.vm.provision :shell do |shell| 
      shell.path =  "https://raw.githubusercontent.com/PacktPublishing/Hands-On-DevOps-with-Vagrant/master/Chapter07/lb.sh"
      shell.args = 1
    end
  end
  config.vm.provider "virtualbox" do |v|
    v.cpus = SERVER_CPU
    v.memory = SERVER_MEMORY
  end
  config.vm.define "web1" do |web1|
    web1.vm.box =  "ubuntu/xenial64"
    web1.vm.network "private_network", ip: IP_vm2
    web1.vm.provision :shell do |shell| 
      shell.path =  "https://raw.githubusercontent.com/PacktPublishing/Hands-On-DevOps-with-Vagrant/master/Chapter07/web.sh"
      shell.args = 1
    end
  end
  config.vm.provider "virtualbox" do |v|
    v.cpus = SERVER_CPU
    v.memory = SERVER_MEMORY
  end

  config.vm.define "web2" do |web2|
    web2.vm.box =  "ubuntu/xenial64"
    web2.vm.network "private_network", ip: IP_vm3
    web2.vm.provision :shell do |shell| 
      shell.path =  "https://raw.githubusercontent.com/PacktPublishing/Hands-On-DevOps-with-Vagrant/master/Chapter07/web.sh"
      shell.args = 2
    end
  end
  config.vm.provider "virtualbox" do |v|
    v.cpus = SERVER_CPU
    v.memory = SERVER_MEMORY
  end
end