# -*- mode: ruby -*-
# vi: set ft=ruby :
SERVER_CPU = 1
SERVER_MEMORY = 1024
IP = "10.0.0.10"

Vagrant.configure("2") do |config|
  config.vm.box = "diaomodou06/nginx"
  config.vm.box_version = "1.0"
  config.vm.hostname = "nginx"
  config.vm.synced_folder "static-website-example/", "/usr/share/nginx/html/"
  config.vm.network "private_network", ip: IP
  config.vm.provider "virtualbox" do |v|
    v.cpus = SERVER_CPU
    v.memory = SERVER_MEMORY
    end
end
